name: TESTBB
favicon: null
layout_spectrum: 0.19094922486692667
typography_spectrum: 0.20926806842908263
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.8435604281257838
  lightness: 0.27738226880319417
  saturation: 0.695201053051278
  rhythmicContrast: 0.29206215869635344
purpose: []
